name: seasonal_multihost
channels:
  - defaults # Order matters tries defaults first
  - conda-forge
dependencies:
  - python=3.8.5
  # - ipython=8.4.0 # Pip install this after the the install
  - jupyter=1.0.0
  - numpy=1.23.3
  - pandas=1.4.4
  - scipy=1.9.3
  - matplotlib=3.5.3
  - scikit-learn=1.1.3
  - seaborn=0.12.0
  - pip #=19.1.1=py37_0
  - sympy=1.10.1
  - statsmodels=0.13.2
  - pip:                            # Packages installed from PyPI
    - jedi==0.18.1
    - numba
    - plotnine
